defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"

checkpoint_path: "outputs/hrnet_w44_1280_fold0/checkpoints/epoch=14-step=24540.ckpt"
minified_json: False
