defaults:
  - _self_
  - preset: augmented_resnet50_ultra_aggressive
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "resnet50_fold0_ultra_aggressive"

checkpoint_path: "outputs/resnet50_fold0/checkpoints/epoch=19-step=14700.ckpt"
minified_json: False
