defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
project_name: "ocr-receipt-detection"

wandb: False
wandb_config:
  project: "ocr-receipt-detection"
  entity: "quriquri7"  # 사용자 이름
  tags: ["baseline", "dbnet"]
  notes: "Receipt Text Detection with DBNet"
  
exp_version: "v1.0"

resume: null

trainer:
  max_epochs: 10
  num_sanity_val_steps: 1
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  deterministic: True
