# @package _global_

models:
  encoder:
    _target_: ${encoder_path}.TimmBackbone
    model_name: 'efficientnet_b4'
    select_features: [1, 2, 3, 4]            # 4개 레이어만 선택 (ResNet50과 동일)
    pretrained: true
