# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [128, 256, 512, 1024]  # HRNet-W44 feature channels
    strides: [4, 8, 16, 32]
    inner_channels: 256
    output_channels: 64
    bias: False
