# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [32, 56, 160, 448]      # EfficientNet-B4 실제 채널 (layer 1-4)
    strides: [4, 8, 16, 32]              # Input layer scale
    inner_channels: 256                   # Hidden layer channel
    output_channels: 64                   # output layer channel
    bias: False
