# @package _global_

defaults:
  - /preset/models/decoder/unet_efficientnet_b4
  - /preset/models/encoder/timm_backbone_efficientnet_b4
  - /preset/models/head/db_head_aggressive
  - /preset/models/loss/db_loss
  - _self_

models:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003  # EfficientNet-B4는 ResNet50보다 낮은 학습률 사용 (60%)
    weight_decay: 0.0001
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 22
    eta_min: 0.00001
