# @package _global_

defaults:
  - base
  - /preset/datasets/db_augmented_resnet50
  - /preset/models/model_resnet50_aggressive
  - /preset/lightning_modules/base
  - _self_

# Override for Fold 2
data:
  train_json_path: /data/ephemeral/home/baseline_code/kfold_results_v2/fold_2/train.json
  val_json_path: /data/ephemeral/home/baseline_code/kfold_results_v2/fold_2/val.json
