# @package _global_

# HRNet-W44 Hybrid Preset
defaults:
  - base
  - /preset/datasets/db_augmented_resnet50
  - /preset/models/model_hrnet_w44_hybrid
  - /preset/lightning_modules/base
  - _self_

exp_name: hrnet_w44_hybrid_progressive
seed: 42
